// ─── Custom View Renderer ───
// Interprets JSON view specs (generated by Wasabi) into widget dashboards.
// Supports: metric, chart, table, text, progress, list, html widgets.
// Data sources: query (from parent data), function_result, static.

import React, { useState, useEffect, useMemo, useRef } from "react";
import { C, FONT, RADIUS, SHADOW, VIEW_PALETTE, getStatusColor } from "../design/tokens.js";
import { ANIM, injectAnimations } from "../design/animations.js";
import { readField, getFieldType, getFieldOptions, computeAggregation, resolveField } from "./_viewHelpers.js";
import * as api from "../lib/api.js";
import { IFRAME_SANDBOX_HELPERS, IFRAME_AUTO_EXECUTE } from "../lib/iframeHelpers.js";

// ─── Formatters ───

function fmt(n) {
  if (n === null || n === undefined) return "0";
  if (Number.isInteger(n)) return n.toLocaleString();
  return n.toLocaleString(undefined, { minimumFractionDigits: 0, maximumFractionDigits: 2 });
}

function pct(n) {
  return (Number(n) || 0).toFixed(1) + "%";
}

// ─── Widget Components ───

function MetricWidget({ widget, resolvedData, schema }) {
  const ds = widget.dataSource || {};
  let value = 0;

  if (ds.type === "static") {
    value = ds.value ?? 0;
  } else if (ds.type === "function_result" && resolvedData) {
    value = typeof resolvedData === "number" ? resolvedData : Array.isArray(resolvedData) ? resolvedData.length : 0;
  } else if (resolvedData && schema && ds.field) {
    value = computeAggregation(resolvedData, schema, ds.field, ds.aggregation || "sum");
  } else if (resolvedData && !ds.field) {
    value = Array.isArray(resolvedData) ? resolvedData.length : 0;
  }

  const palIdx = widget.style?.accentColor ?? 5;
  const color = VIEW_PALETTE[palIdx]?.hex || C.accent;

  return (
    <div style={{
      display: "flex", flexDirection: "column", gap: 6,
      alignItems: "center", justifyContent: "center",
      padding: "28px 16px", textAlign: "center", minHeight: 100,
    }}>
      <span style={{
        fontSize: 36, fontWeight: 700, color,
        fontVariantNumeric: "tabular-nums", letterSpacing: "-0.02em",
      }}>
        {fmt(value)}
      </span>
      {widget.title && (
        <span style={{ fontSize: 12, color: C.darkMuted, fontWeight: 500, textTransform: "uppercase", letterSpacing: "0.06em" }}>
          {widget.title}
        </span>
      )}
    </div>
  );
}

function ChartWidget({ widget, resolvedData, schema }) {
  const [hoverIdx, setHoverIdx] = useState(null);
  const ds = widget.dataSource || {};
  const chartType = widget.chartType || "bar";

  const chartData = useMemo(() => {
    if (!resolvedData || !Array.isArray(resolvedData)) return [];

    // If static data array with {category, value}
    if (ds.type === "static" || ds.type === "function_result") {
      return resolvedData.map((d, i) => ({
        category: d.category || d.label || d.name || `Item ${i + 1}`,
        value: d.value ?? d.count ?? 0,
        color: VIEW_PALETTE[(i + 5) % VIEW_PALETTE.length]?.hex || C.accent,
      }));
    }

    // Query-based: group by category field, aggregate value field
    const catField = ds.categoryField;
    const valField = ds.valueField;
    const agg = ds.aggregation || (valField ? "sum" : "count");
    if (!catField) return [];

    const groups = {};
    for (const page of resolvedData) {
      const cat = readField(page, catField) || "Unknown";
      if (!groups[cat]) groups[cat] = [];
      groups[cat].push(page);
    }

    const optNames = schema ? getFieldOptions(schema, catField).map(o => o.name) : [];

    return Object.entries(groups).map(([category, pages]) => {
      let value = 0;
      if (agg === "count") {
        value = pages.length;
      } else if (valField) {
        const nums = pages.map(p => readField(p, valField)).filter(v => typeof v === "number");
        if (agg === "sum") value = nums.reduce((a, b) => a + b, 0);
        else if (agg === "avg") value = nums.length ? nums.reduce((a, b) => a + b, 0) / nums.length : 0;
        else if (agg === "min") value = nums.length ? Math.min(...nums) : 0;
        else if (agg === "max") value = nums.length ? Math.max(...nums) : 0;
      } else {
        value = pages.length;
      }
      return { category, value, color: getStatusColor(category, optNames).hex || C.accent, count: pages.length };
    }).sort((a, b) => chartType === "line" ? 0 : b.value - a.value);
  }, [resolvedData, ds, schema, chartType]);

  const maxValue = Math.max(...chartData.map(d => d.value), 1);
  const total = chartData.reduce((s, d) => s + d.value, 0);

  if (!chartData.length) {
    return <div style={{ padding: 24, color: C.darkMuted, fontSize: 13, textAlign: "center" }}>No chart data.</div>;
  }

  if (chartType === "bar") return <MiniBar data={chartData} maxValue={maxValue} hover={hoverIdx} setHover={setHoverIdx} />;
  if (chartType === "pie") return <MiniPie data={chartData} total={total} hover={hoverIdx} setHover={setHoverIdx} />;
  if (chartType === "line") return <MiniLine data={chartData} maxValue={maxValue} hover={hoverIdx} setHover={setHoverIdx} />;
  return null;
}

// ─── Mini Charts (self-contained SVG) ───

function MiniBar({ data, maxValue, hover, setHover }) {
  const barH = 24, gap = 6, labelW = 100, chartW = 320;
  const svgH = data.length * (barH + gap) + gap;
  return (
    <svg width="100%" viewBox={`0 0 ${labelW + chartW + 60} ${svgH}`} style={{ overflow: "visible" }}>
      {data.map((d, i) => {
        const y = i * (barH + gap) + gap;
        const barW = Math.max(3, (d.value / maxValue) * chartW);
        return (
          <g key={i} onMouseEnter={() => setHover(i)} onMouseLeave={() => setHover(null)} style={{ cursor: "pointer" }}>
            <text x={labelW - 6} y={y + barH / 2 + 1} textAnchor="end" fontSize={11} fill={hover === i ? C.darkText : C.darkMuted} fontFamily={FONT} dominantBaseline="middle">
              {d.category.length > 14 ? d.category.slice(0, 14) + "\u2026" : d.category}
            </text>
            <rect x={labelW} y={y} width={barW} height={barH} rx={barH / 2} fill={d.color} opacity={hover === i ? 1 : 0.8} style={{ transition: "opacity 0.15s" }} />
            <text x={labelW + barW + 6} y={y + barH / 2 + 1} fontSize={11} fill={C.darkText} fontFamily={FONT} dominantBaseline="middle" fontWeight={600}>
              {fmt(d.value)}
            </text>
          </g>
        );
      })}
    </svg>
  );
}

function MiniPie({ data, total, hover, setHover }) {
  const cx = 80, cy = 80, outerR = 70, innerR = 42;
  let startAngle = -Math.PI / 2;
  const arcs = data.map((d) => {
    const fraction = total > 0 ? d.value / total : 0;
    const sweep = fraction * Math.PI * 2;
    const endAngle = startAngle + sweep;
    const x1 = cx + outerR * Math.cos(startAngle), y1 = cy + outerR * Math.sin(startAngle);
    const x2 = cx + outerR * Math.cos(endAngle), y2 = cy + outerR * Math.sin(endAngle);
    const ix1 = cx + innerR * Math.cos(endAngle), iy1 = cy + innerR * Math.sin(endAngle);
    const ix2 = cx + innerR * Math.cos(startAngle), iy2 = cy + innerR * Math.sin(startAngle);
    const largeArc = sweep > Math.PI ? 1 : 0;
    const path = `M ${x1} ${y1} A ${outerR} ${outerR} 0 ${largeArc} 1 ${x2} ${y2} L ${ix1} ${iy1} A ${innerR} ${innerR} 0 ${largeArc} 0 ${ix2} ${iy2} Z`;
    startAngle = endAngle;
    return { ...d, path, fraction };
  });

  return (
    <div style={{ display: "flex", alignItems: "center", gap: 24, flexWrap: "wrap", justifyContent: "center" }}>
      <svg width={160} height={160} viewBox="0 0 160 160">
        {arcs.map((a, i) => (
          <path key={i} d={a.path} fill={a.color} opacity={hover === i ? 1 : 0.85}
            style={{ transition: "opacity 0.15s", cursor: "pointer" }}
            onMouseEnter={() => setHover(i)} onMouseLeave={() => setHover(null)} />
        ))}
        <text x={cx} y={cy - 4} textAnchor="middle" fontSize={16} fontWeight={700} fill={C.darkText} fontFamily={FONT}>{fmt(total)}</text>
        <text x={cx} y={cy + 12} textAnchor="middle" fontSize={9} fill={C.darkMuted} fontFamily={FONT}>Total</text>
      </svg>
      <div style={{ display: "flex", flexDirection: "column", gap: 5 }}>
        {arcs.map((a, i) => (
          <div key={i} style={{ display: "flex", alignItems: "center", gap: 6, opacity: hover === i ? 1 : 0.8, transition: "opacity 0.15s", cursor: "pointer" }}
            onMouseEnter={() => setHover(i)} onMouseLeave={() => setHover(null)}>
            <div style={{ width: 8, height: 8, borderRadius: "50%", background: a.color, flexShrink: 0 }} />
            <span style={{ fontSize: 11, color: C.darkText, minWidth: 60 }}>{a.category}</span>
            <span style={{ fontSize: 11, color: C.darkMuted, fontWeight: 600 }}>{fmt(a.value)}</span>
          </div>
        ))}
      </div>
    </div>
  );
}

function MiniLine({ data, maxValue, hover, setHover }) {
  const W = 400, H = 200, padL = 40, padR = 10, padT = 16, padB = 30;
  const chartW = W - padL - padR, chartH = H - padT - padB;
  if (data.length < 2) return <div style={{ color: C.darkMuted, fontSize: 13 }}>Need 2+ points.</div>;
  const pts = data.map((d, i) => ({ x: padL + (i / (data.length - 1)) * chartW, y: padT + chartH - (d.value / maxValue) * chartH, ...d }));
  const polyline = pts.map(p => `${p.x},${p.y}`).join(" ");

  return (
    <svg width="100%" viewBox={`0 0 ${W} ${H}`} style={{ overflow: "visible" }}>
      {[0, 1, 2, 3, 4].map(i => {
        const y = padT + (i / 4) * chartH;
        return <line key={i} x1={padL} y1={y} x2={W - padR} y2={y} stroke={C.darkBorder} strokeWidth={1} />;
      })}
      <polygon points={`${pts[0].x},${padT + chartH} ${polyline} ${pts[pts.length - 1].x},${padT + chartH}`} fill={C.accent} opacity={0.08} />
      <polyline points={polyline} fill="none" stroke={C.accent} strokeWidth={2} strokeLinejoin="round" strokeLinecap="round" />
      {pts.map((p, i) => (
        <g key={i} onMouseEnter={() => setHover(i)} onMouseLeave={() => setHover(null)} cursor="pointer">
          <circle cx={p.x} cy={p.y} r={hover === i ? 5 : 3} fill={C.accent} stroke={C.dark} strokeWidth={2} />
          <text x={p.x} y={H - 6} textAnchor="middle" fontSize={8} fill={C.darkMuted} fontFamily={FONT}>
            {(p.category || "").length > 8 ? p.category.slice(0, 8) + "\u2026" : p.category}
          </text>
          {hover === i && (
            <text x={p.x} y={p.y - 10} textAnchor="middle" fontSize={11} fontWeight={700} fill={C.darkText} fontFamily={FONT}>{fmt(p.value)}</text>
          )}
        </g>
      ))}
    </svg>
  );
}

// ─── Table Widget ───

function TableWidget({ widget, resolvedData, schema }) {
  const columns = widget.columns || [];
  const limit = widget.dataSource?.limit || 50;
  const rows = Array.isArray(resolvedData) ? resolvedData.slice(0, limit) : [];

  if (!rows.length) {
    return <div style={{ padding: 16, color: C.darkMuted, fontSize: 12, textAlign: "center" }}>No data.</div>;
  }

  // Resolve columns: use widget.columns, or infer from first row keys
  const cols = columns.length > 0 ? columns : Object.keys(rows[0]).filter(k => !k.startsWith("_"));

  // Check if rows are Notion page objects or plain objects
  const isNotionPage = rows[0]?.properties !== undefined;

  const getCellValue = (row, col) => {
    if (isNotionPage) {
      const val = readField(row, col);
      if (val === null || val === undefined) return "";
      if (typeof val === "object" && val.start) return val.start;
      return String(val);
    }
    const v = row[col];
    if (v === null || v === undefined) return "";
    if (typeof v === "number") return fmt(v);
    return String(v);
  };

  return (
    <div style={{ overflowX: "auto", maxHeight: 300, overflowY: "auto" }}>
      <table style={{ width: "100%", borderCollapse: "collapse", fontSize: 12, fontFamily: FONT }}>
        <thead>
          <tr>
            {cols.map(col => (
              <th key={col} style={{
                textAlign: "left", padding: "8px 10px", fontSize: 10, fontWeight: 600,
                textTransform: "uppercase", letterSpacing: "0.06em", color: C.darkMuted,
                borderBottom: `2px solid ${C.darkBorder}`, whiteSpace: "nowrap",
                position: "sticky", top: 0, background: C.darkSurf, zIndex: 1,
              }}>
                {col}
              </th>
            ))}
          </tr>
        </thead>
        <tbody>
          {rows.map((row, i) => (
            <tr key={row.id || i} style={{ transition: "background 0.1s" }}
              onMouseEnter={e => e.currentTarget.style.background = `${C.darkSurf2}88`}
              onMouseLeave={e => e.currentTarget.style.background = "transparent"}>
              {cols.map(col => (
                <td key={col} style={{
                  padding: "6px 10px", borderBottom: `1px solid ${C.edgeLine}`,
                  color: C.darkText, fontSize: 12, lineHeight: 1.4,
                  whiteSpace: "nowrap", overflow: "hidden", textOverflow: "ellipsis", maxWidth: 200,
                }}>
                  {getCellValue(row, col)}
                </td>
              ))}
            </tr>
          ))}
        </tbody>
      </table>
    </div>
  );
}

// ─── Text Widget ───

function TextWidget({ widget }) {
  return (
    <div style={{ padding: "16px 20px", fontSize: 13, lineHeight: 1.6, color: C.darkText, whiteSpace: "pre-wrap" }}>
      {widget.content || ""}
    </div>
  );
}

// ─── Progress Widget ───

function ProgressWidget({ widget, resolvedData }) {
  const ds = widget.dataSource || {};
  let current = ds.current ?? 0;
  let target = ds.target ?? 100;

  if (ds.type === "function_result" && resolvedData && typeof resolvedData === "object" && !Array.isArray(resolvedData)) {
    current = resolvedData.current ?? current;
    target = resolvedData.target ?? target;
  }

  const ratio = target > 0 ? Math.min(current / target, 1) : 0;
  const barColor = ratio >= 0.8 ? "#4CAF50" : ratio >= 0.5 ? "#FF9800" : "#f44336";

  return (
    <div style={{ padding: "20px 16px", display: "flex", flexDirection: "column", gap: 10, alignItems: "center" }}>
      {widget.title && <span style={{ fontSize: 12, color: C.darkMuted, fontWeight: 500, textTransform: "uppercase", letterSpacing: "0.06em" }}>{widget.title}</span>}
      <div style={{ width: "100%", height: 12, background: C.darkSurf2, borderRadius: RADIUS.pill, overflow: "hidden" }}>
        <div style={{
          width: `${ratio * 100}%`, height: "100%", background: barColor,
          borderRadius: RADIUS.pill, transition: "width 0.5s cubic-bezier(0.22, 1.2, 0.36, 1)",
        }} />
      </div>
      <span style={{ fontSize: 20, fontWeight: 700, color: barColor, fontVariantNumeric: "tabular-nums" }}>
        {pct(ratio * 100)}
      </span>
      <span style={{ fontSize: 11, color: C.darkMuted }}>{fmt(current)} / {fmt(target)}</span>
    </div>
  );
}

// ─── List Widget ───

function ListWidget({ widget, resolvedData }) {
  const labelField = widget.labelField || "label";
  const valueField = widget.valueField || "value";
  const items = Array.isArray(resolvedData) ? resolvedData : [];

  if (!items.length) {
    return <div style={{ padding: 16, color: C.darkMuted, fontSize: 12, textAlign: "center" }}>No items.</div>;
  }

  const maxVal = Math.max(...items.map(d => Number(d[valueField]) || 0), 1);

  return (
    <div style={{ display: "flex", flexDirection: "column", gap: 2, padding: "8px 0" }}>
      {items.map((item, i) => {
        const label = item[labelField] || `#${i + 1}`;
        const value = Number(item[valueField]) || 0;
        const barW = (value / maxVal) * 100;
        const palIdx = (i + 5) % VIEW_PALETTE.length;
        const color = VIEW_PALETTE[palIdx]?.hex || C.accent;

        return (
          <div key={i} style={{ display: "flex", alignItems: "center", gap: 8, padding: "6px 16px" }}>
            <span style={{ fontSize: 10, color: C.darkMuted, width: 18, textAlign: "right", flexShrink: 0, fontWeight: 600 }}>
              {i + 1}
            </span>
            <div style={{ flex: 1, position: "relative", height: 24, display: "flex", alignItems: "center" }}>
              <div style={{
                position: "absolute", left: 0, top: 2, bottom: 2,
                width: `${barW}%`, background: color, opacity: 0.15, borderRadius: RADIUS.sm,
                transition: "width 0.3s ease",
              }} />
              <span style={{ fontSize: 12, color: C.darkText, position: "relative", paddingLeft: 6 }}>
                {String(label).length > 30 ? String(label).slice(0, 30) + "\u2026" : label}
              </span>
            </div>
            <span style={{ fontSize: 12, fontWeight: 600, color, fontVariantNumeric: "tabular-nums", flexShrink: 0 }}>
              {fmt(value)}
            </span>
          </div>
        );
      })}
    </div>
  );
}

// ─── HTML Widget (sandboxed iframe for custom rendering) ───

function HtmlWidget({ widget, resolvedData }) {
  const iframeRef = useRef(null);
  const [iframeHeight, setIframeHeight] = useState(widget.height || 300);

  // Build theme colors for injection
  const themeColors = {
    bg: C.dark, surface: C.darkSurf, surfaceRaised: C.darkSurf2,
    border: C.darkBorder, text: C.darkText, muted: C.darkMuted,
    accent: C.accent, accentDim: C.accentDim,
  };

  // resolvedData is either { code, html } or a raw HTML/code string
  const code = typeof resolvedData === "string"
    ? resolvedData
    : resolvedData?.code || resolvedData?.html || "";

  if (!code) {
    return (
      <div style={{ padding: 24, color: C.darkMuted, fontSize: 12, textAlign: "center" }}>
        No HTML content to render.
      </div>
    );
  }

  // Determine if `code` is a full HTML document or a JS snippet
  const isFullHtml = code.trim().startsWith("<!") || code.trim().startsWith("<html") || code.trim().startsWith("<div");
  const isJsCode = !isFullHtml;

  const srcdoc = isFullHtml
    ? code
    : `<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<style>
  *, *::before, *::after { box-sizing: border-box; margin: 0; padding: 0; }
  body {
    font-family: 'Outfit','DM Sans',sans-serif;
    font-size: 13px;
    color: ${themeColors.text};
    background: transparent;
    overflow: hidden;
    display: flex;
    align-items: center;
    justify-content: center;
    min-height: 100%;
  }
  ::-webkit-scrollbar { width: 4px; height: 4px; }
  ::-webkit-scrollbar-thumb { background: ${themeColors.border}; border-radius: 4px; }
</style>
</head>
<body>
<div id="root" style="width:100%;height:100%;display:flex;align-items:center;justify-content:center;"></div>
<script>
window.wasabi = {
  colors: ${JSON.stringify(themeColors)},
  root: document.getElementById('root'),
};
${IFRAME_SANDBOX_HELPERS}
try {
  ${code}

  ${IFRAME_AUTO_EXECUTE}
} catch(err) {
  document.getElementById('root').innerHTML =
    '<div style="color:#E05252;padding:12px;font-size:12px;">' +
    '<strong>Render Error:</strong> ' + err.message + '</div>';
}
</script>
</body>
</html>`;

  return (
    <iframe
      ref={iframeRef}
      srcDoc={srcdoc}
      sandbox="allow-scripts"
      style={{
        width: "100%",
        height: iframeHeight,
        border: "none",
        background: "transparent",
        display: "block",
        borderRadius: RADIUS.lg,
      }}
      title={widget.title || "Custom Widget"}
    />
  );
}

// ─── Widget Renderer (dispatcher) ───

const WIDGET_MAP = {
  metric: MetricWidget,
  chart: ChartWidget,
  table: TableWidget,
  text: TextWidget,
  progress: ProgressWidget,
  list: ListWidget,
  html: HtmlWidget,
};

function WidgetCard({ widget, index, resolvedData, schema }) {
  const WidgetComponent = WIDGET_MAP[widget.type];
  if (!WidgetComponent) {
    return (
      <div style={{ padding: 16, color: C.darkMuted, fontSize: 12 }}>
        Unknown widget type: "{widget.type}"
      </div>
    );
  }

  return (
    <div style={{
      background: C.darkSurf,
      border: `1px solid ${C.darkBorder}`,
      borderRadius: RADIUS.xl,
      overflow: "hidden",
      gridColumn: `span ${widget.span || 1}`,
      animation: ANIM.settleIn(index * 0.05),
      transition: "border-color 0.15s, box-shadow 0.15s",
      display: "flex",
      flexDirection: "column",
    }}
      onMouseEnter={e => { e.currentTarget.style.borderColor = C.accent + "44"; e.currentTarget.style.boxShadow = SHADOW.cardHover; }}
      onMouseLeave={e => { e.currentTarget.style.borderColor = C.darkBorder; e.currentTarget.style.boxShadow = "none"; }}
    >
      {/* Widget title bar (except for text/metric which embed their own) */}
      {widget.title && widget.type !== "metric" && widget.type !== "text" && (
        <div style={{
          padding: "12px 16px 8px",
          fontSize: 12, fontWeight: 600, color: C.darkText,
          letterSpacing: "0.01em",
        }}>
          {widget.title}
        </div>
      )}
      <div style={{ flex: 1, display: "flex", flexDirection: "column", justifyContent: "center" }}>
        <WidgetComponent widget={widget} resolvedData={resolvedData} schema={schema} />
      </div>
    </div>
  );
}

// ─── Main CustomView Component ───

export default function CustomView({ data = [], schema, config = {} }) {
  const [viewSpec, setViewSpec] = useState(config.viewSpec || null);
  const [widgetData, setWidgetData] = useState({});
  const [loading, setLoading] = useState(false);

  // Inject animations once
  useEffect(() => { injectAnimations(); }, []);

  // Load view spec from custom function if functionId provided
  useEffect(() => {
    if (config.viewSpec) {
      setViewSpec(config.viewSpec);
      return;
    }
    if (!config.functionId) return;

    setLoading(true);
    api.getCustomFunction(config.functionId)
      .then(fn => {
        const outputs = typeof fn.outputs === "string" ? JSON.parse(fn.outputs) : fn.outputs;
        if (outputs?.spec) setViewSpec(outputs.spec);
        else if (outputs?.version && outputs?.widgets) setViewSpec(outputs);
        else setViewSpec(null);
      })
      .catch(() => setViewSpec(null))
      .finally(() => setLoading(false));
  }, [config.functionId, config.viewSpec]);

  // Resolve per-widget data
  useEffect(() => {
    if (!viewSpec?.widgets) return;

    const resolveAll = async () => {
      const resolved = {};

      for (const widget of viewSpec.widgets) {
        const ds = widget.dataSource;
        if (!ds) {
          resolved[widget.id] = null;
          continue;
        }

        try {
          if (ds.type === "static") {
            // Static data is inline
            resolved[widget.id] = ds.data ?? ds.value ?? null;
          } else if (ds.type === "query") {
            // Filter parent data by databaseId if provided
            if (ds.databaseId) {
              let filtered = data.filter(r => r._databaseId === ds.databaseId);
              // Apply sorts if specified
              if (ds.sorts?.length) {
                const sort = ds.sorts[0];
                const dir = sort.direction === "descending" ? -1 : 1;
                filtered.sort((a, b) => {
                  const va = readField(a, sort.property);
                  const vb = readField(b, sort.property);
                  if (va < vb) return -dir;
                  if (va > vb) return dir;
                  return 0;
                });
              }
              if (ds.limit) filtered = filtered.slice(0, ds.limit);
              resolved[widget.id] = filtered;
            } else {
              // Use all parent data
              resolved[widget.id] = ds.limit ? data.slice(0, ds.limit) : data;
            }
          } else if (ds.type === "function_result" && ds.functionId) {
            // Fetch and execute a custom function
            try {
              const fn = await api.getCustomFunction(ds.functionId);
              if (fn?.code) {
                // For html widgets, pass the raw code for iframe rendering
                if (widget.type === "html") {
                  resolved[widget.id] = { code: fn.code, html: fn.outputs?.html };
                } else {
                  const { executeSandbox } = await import("../agent/toolExecutor.js");
                  const res = executeSandbox(fn.code, {}, fn.name || "Custom function");
                  resolved[widget.id] = res?.success ? res.result : null;
                }
              } else {
                resolved[widget.id] = null;
              }
            } catch {
              resolved[widget.id] = null;
            }
          }
        } catch {
          resolved[widget.id] = null;
        }
      }

      setWidgetData(resolved);
    };

    resolveAll();
  }, [viewSpec, data]);

  // Loading state
  if (loading) {
    return (
      <div style={{ padding: 40, textAlign: "center", color: C.darkMuted, fontSize: 14, fontFamily: FONT }}>
        Loading view...
      </div>
    );
  }

  // No spec
  if (!viewSpec) {
    return (
      <div style={{ padding: 40, textAlign: "center", color: C.darkMuted, fontSize: 14, fontFamily: FONT }}>
        No view spec configured. Set a functionId or viewSpec in the view config.
      </div>
    );
  }

  const { layout = "grid", columns = 2, widgets = [] } = viewSpec;

  return (
    <div style={{ fontFamily: FONT, padding: 16 }}>
      {/* Title */}
      {viewSpec.title && (
        <div style={{
          fontSize: 16, fontWeight: 700, color: C.darkText,
          marginBottom: 16, padding: "0 4px",
          animation: ANIM.fadeUp(0),
        }}>
          {viewSpec.title}
        </div>
      )}

      {/* Widget grid */}
      <div style={{
        display: "grid",
        gridTemplateColumns: layout === "stack" ? "1fr" : layout === "columns" ? `repeat(${columns}, 1fr)` : `repeat(auto-fill, minmax(260px, 1fr))`,
        gap: 16,
      }}>
        {widgets.map((widget, i) => (
          <WidgetCard
            key={widget.id || i}
            widget={widget}
            index={i}
            resolvedData={widgetData[widget.id]}
            schema={schema}
          />
        ))}
      </div>
    </div>
  );
}
