// ─── Extensions Handlers ───
// CRUD for `extensions` (template definitions) and `extension_snapshots`
// (concrete generated reports). Template HTML lives in D1 as text; rendered
// snapshot HTML lives in R2 under `extensions/{ext_slug}/{snap_slug}.html`.
//
// MCP is the primary authoring surface (templates registered by Claude
// reading a local HTML file and passing contents as an arg). Snapshots are
// generated by MCP from validated DATA matching the template's JSON Schema.

import { safeParseJSON } from '../utils.js';

// ════════════════════════════════════════════════════════════════════
// Helpers
// ════════════════════════════════════════════════════════════════════

const REPORTS_PAGE_ID = 'system_reports';

function rowToExtension(row) {
  if (!row) return null;
  return {
    ...row,
    data_schema: safeParseJSON(row.data_schema) || {},
    sample_data: safeParseJSON(row.sample_data) || {},
    ext_config:  safeParseJSON(row.ext_config)  || {},
    // Legacy rows may lack type — default to 'mcp_generated' for clients.
    type: row.type || 'mcp_generated',
  };
}

function rowToSnapshot(row) {
  if (!row) return null;
  return {
    ...row,
    data: safeParseJSON(row.data) || {},
  };
}

function slugify(s) {
  return String(s || '')
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-|-$/g, '')
    .slice(0, 64);
}

// ════════════════════════════════════════════════════════════════════
// Minimal JSON Schema validator (hand-written, ~100 lines)
// ════════════════════════════════════════════════════════════════════
// Supports the subset we need for extension DATA validation:
//   type (string|number|integer|boolean|object|array|null|any)
//   required (string[])
//   properties (object)
//   additionalProperties (boolean)
//   items (schema)
//   enum (any[])
//   minimum / maximum (numbers)
//   minLength / maxLength (strings)
//   minItems / maxItems (arrays)
//   pattern (string regex)
//
// Returns { ok: true } on success or { ok: false, errors: [...] } on failure.
// Each error is { path, message }.

export function validateData(data, schema, path = '$') {
  const errors = [];
  if (!schema || typeof schema !== 'object') return { ok: true };
  const t = schema.type;

  // Type check
  const actualType = Array.isArray(data) ? 'array' : data === null ? 'null' : typeof data;
  const matchesType = (expected) => {
    if (expected === 'any' || !expected) return true;
    if (expected === 'integer') return actualType === 'number' && Number.isInteger(data);
    return expected === actualType;
  };
  if (t && !(Array.isArray(t) ? t.some(matchesType) : matchesType(t))) {
    errors.push({ path, message: `expected ${Array.isArray(t) ? t.join('|') : t}, got ${actualType}` });
    return { ok: false, errors };
  }

  // Enum
  if (Array.isArray(schema.enum) && schema.enum.length > 0) {
    const match = schema.enum.some((v) => JSON.stringify(v) === JSON.stringify(data));
    if (!match) errors.push({ path, message: `value not in enum: ${JSON.stringify(schema.enum).slice(0, 200)}` });
  }

  // Numbers
  if (actualType === 'number') {
    if (typeof schema.minimum === 'number' && data < schema.minimum) {
      errors.push({ path, message: `value ${data} is less than minimum ${schema.minimum}` });
    }
    if (typeof schema.maximum === 'number' && data > schema.maximum) {
      errors.push({ path, message: `value ${data} is greater than maximum ${schema.maximum}` });
    }
  }

  // Strings
  if (actualType === 'string') {
    if (typeof schema.minLength === 'number' && data.length < schema.minLength) {
      errors.push({ path, message: `string shorter than minLength ${schema.minLength}` });
    }
    if (typeof schema.maxLength === 'number' && data.length > schema.maxLength) {
      errors.push({ path, message: `string longer than maxLength ${schema.maxLength}` });
    }
    if (typeof schema.pattern === 'string') {
      try {
        const re = new RegExp(schema.pattern);
        if (!re.test(data)) errors.push({ path, message: `string does not match pattern ${schema.pattern}` });
      } catch { /* invalid regex — skip */ }
    }
  }

  // Arrays
  if (actualType === 'array') {
    if (typeof schema.minItems === 'number' && data.length < schema.minItems) {
      errors.push({ path, message: `array shorter than minItems ${schema.minItems}` });
    }
    if (typeof schema.maxItems === 'number' && data.length > schema.maxItems) {
      errors.push({ path, message: `array longer than maxItems ${schema.maxItems}` });
    }
    if (schema.items) {
      for (let i = 0; i < data.length; i++) {
        const sub = validateData(data[i], schema.items, `${path}[${i}]`);
        if (!sub.ok) errors.push(...sub.errors);
      }
    }
  }

  // Objects
  if (actualType === 'object') {
    if (Array.isArray(schema.required)) {
      for (const key of schema.required) {
        if (!(key in data)) errors.push({ path: `${path}.${key}`, message: 'required property missing' });
      }
    }
    if (schema.properties && typeof schema.properties === 'object') {
      for (const [key, sub] of Object.entries(schema.properties)) {
        if (key in data) {
          const r = validateData(data[key], sub, `${path}.${key}`);
          if (!r.ok) errors.push(...r.errors);
        }
      }
      if (schema.additionalProperties === false) {
        const allowed = new Set(Object.keys(schema.properties));
        for (const key of Object.keys(data)) {
          if (!allowed.has(key)) errors.push({ path: `${path}.${key}`, message: 'additional property not allowed' });
        }
      }
    }
  }

  return errors.length === 0 ? { ok: true } : { ok: false, errors };
}

// ════════════════════════════════════════════════════════════════════
// Extension CRUD
// ════════════════════════════════════════════════════════════════════

export async function handleListExtensions(env, url, jsonResponse) {
  const status = url.searchParams.get('status');
  const type   = url.searchParams.get('type');
  let query = 'SELECT * FROM extensions';
  const conditions = [];
  const params = [];
  if (status) { conditions.push('status = ?'); params.push(status); }
  if (type)   { conditions.push('type = ?');   params.push(type); }
  if (conditions.length) query += ' WHERE ' + conditions.join(' AND ');
  query += ' ORDER BY updated_at DESC';
  const { results } = await env.DB.prepare(query).bind(...params).all();
  return jsonResponse({ extensions: (results || []).map(rowToExtension) });
}

export async function handleGetExtension(env, id, jsonResponse) {
  // Accept either UUID id or slug
  const row = await env.DB.prepare(
    'SELECT * FROM extensions WHERE id = ? OR slug = ? LIMIT 1'
  ).bind(id, id).first();
  if (!row) return jsonResponse({ _error: 'Extension not found' }, 404);
  return jsonResponse(rowToExtension(row));
}

export async function handleCreateExtension(env, body, user, jsonResponse) {
  const { name } = body;
  // Type: 'mcp_generated' (default) or 'data_collection'. Data collection
  // extensions don't need `html` — their UI is rendered natively in React.
  const type = body.type === 'data_collection' ? 'data_collection' : 'mcp_generated';
  const html = body.html || '';
  if (!name) return jsonResponse({ _error: 'name required' }, 400);
  if (type === 'mcp_generated' && !html) {
    return jsonResponse({ _error: 'html required for mcp_generated extensions' }, 400);
  }

  const id = body.id || `ext_${crypto.randomUUID().replace(/-/g, '').slice(0, 12)}`;
  const slug = body.slug ? slugify(body.slug) : slugify(name);
  if (!slug) return jsonResponse({ _error: 'slug could not be derived (provide explicit slug)' }, 400);

  // Check slug uniqueness
  const existing = await env.DB.prepare('SELECT id FROM extensions WHERE slug = ?').bind(slug).first();
  if (existing) return jsonResponse({ _error: `slug '${slug}' already in use` }, 409);

  await env.DB.prepare(
    `INSERT INTO extensions
       (id, slug, name, icon, description, definition, html, data_schema, sample_data, theme_preference, version, status, type, ext_config, created_by, created_at, updated_at)
     VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, 1, ?, ?, ?, ?, datetime('now'), datetime('now'))`
  ).bind(
    id,
    slug,
    name,
    body.icon || '',
    body.description || '',
    body.definition || '',
    html,
    JSON.stringify(body.data_schema || {}),
    JSON.stringify(body.sample_data || {}),
    body.theme_preference || 'inherit',
    body.status || 'active',
    type,
    JSON.stringify(body.ext_config || {}),
    user?.sub || ''
  ).run();

  return jsonResponse({ ok: true, id, slug, type }, 201);
}

export async function handleUpdateExtension(env, id, body, jsonResponse) {
  const row = await env.DB.prepare('SELECT * FROM extensions WHERE id = ? OR slug = ? LIMIT 1').bind(id, id).first();
  if (!row) return jsonResponse({ _error: 'Extension not found' }, 404);

  const sets = [];
  const vals = [];
  const allowedScalar = ['name', 'icon', 'description', 'definition', 'html', 'theme_preference', 'status', 'type'];
  for (const key of allowedScalar) {
    if (key in body) { sets.push(`${key} = ?`); vals.push(body[key]); }
  }
  if ('data_schema' in body) { sets.push('data_schema = ?'); vals.push(JSON.stringify(body.data_schema || {})); }
  if ('sample_data' in body) { sets.push('sample_data = ?'); vals.push(JSON.stringify(body.sample_data || {})); }
  if ('ext_config'  in body) { sets.push('ext_config = ?');  vals.push(JSON.stringify(body.ext_config  || {})); }
  if ('slug' in body) {
    const newSlug = slugify(body.slug);
    if (!newSlug) return jsonResponse({ _error: 'invalid slug' }, 400);
    if (newSlug !== row.slug) {
      const conflict = await env.DB.prepare('SELECT id FROM extensions WHERE slug = ? AND id != ?').bind(newSlug, row.id).first();
      if (conflict) return jsonResponse({ _error: `slug '${newSlug}' already in use` }, 409);
    }
    sets.push('slug = ?'); vals.push(newSlug);
  }

  if (sets.length === 0) return jsonResponse({ _error: 'No valid fields to update' }, 400);

  // Bump version if html, data_schema, or sample_data changed
  if ('html' in body || 'data_schema' in body || 'sample_data' in body) {
    sets.push('version = version + 1');
  }
  sets.push("updated_at = datetime('now')");
  vals.push(row.id);

  await env.DB.prepare(`UPDATE extensions SET ${sets.join(', ')} WHERE id = ?`).bind(...vals).run();
  return jsonResponse({ ok: true, id: row.id });
}

export async function handleDeleteExtension(env, id, jsonResponse) {
  const row = await env.DB.prepare('SELECT id, type FROM extensions WHERE id = ? OR slug = ? LIMIT 1').bind(id, id).first();
  if (!row) return jsonResponse({ _error: 'Extension not found' }, 404);

  // Don't allow deletion if snapshots exist (avoid orphans)
  const snapCount = await env.DB.prepare(
    'SELECT COUNT(*) as count FROM extension_snapshots WHERE extension_id = ?'
  ).bind(row.id).first();
  if (snapCount?.count > 0) {
    return jsonResponse({
      _error: `Cannot delete: ${snapCount.count} snapshot(s) exist. Delete snapshots first or archive the extension instead.`,
    }, 409);
  }

  // Data Collection extensions may have items + submissions. Refuse if any
  // submissions exist; caller can archive instead. Empty catalogs are fine.
  if ((row.type || 'mcp_generated') === 'data_collection') {
    const subCount = await env.DB.prepare(
      'SELECT COUNT(*) as count FROM dc_submissions WHERE extension_id = ?'
    ).bind(row.id).first();
    if (subCount?.count > 0) {
      return jsonResponse({
        _error: `Cannot delete: ${subCount.count} submission(s) exist. Archive the extension or delete submissions first.`,
      }, 409);
    }
    // Clean up items + share links (empty catalog + tokens are safe to drop)
    await env.DB.prepare('DELETE FROM dc_items WHERE extension_id = ?').bind(row.id).run();
    await env.DB.prepare('DELETE FROM dc_share_links WHERE extension_id = ?').bind(row.id).run();
  }

  await env.DB.prepare('DELETE FROM extensions WHERE id = ?').bind(row.id).run();
  return jsonResponse({ ok: true, id: row.id });
}

// ════════════════════════════════════════════════════════════════════
// Snapshot CRUD + lifecycle (used in Phase 4)
// ════════════════════════════════════════════════════════════════════

export async function handleListSnapshots(env, url, extensionId, jsonResponse) {
  const status = url.searchParams.get('status');
  // extensionId is optional — if null, list across all extensions
  let query = 'SELECT * FROM extension_snapshots';
  const conditions = [];
  const params = [];
  if (extensionId) {
    // Resolve to canonical id (caller may pass slug)
    const ext = await env.DB.prepare(
      'SELECT id FROM extensions WHERE id = ? OR slug = ? LIMIT 1'
    ).bind(extensionId, extensionId).first();
    if (!ext) return jsonResponse({ _error: 'Extension not found' }, 404);
    conditions.push('extension_id = ?');
    params.push(ext.id);
  }
  if (status) { conditions.push('status = ?'); params.push(status); }
  if (conditions.length) query += ' WHERE ' + conditions.join(' AND ');
  query += ' ORDER BY generated_at DESC LIMIT 200';
  const { results } = await env.DB.prepare(query).bind(...params).all();
  return jsonResponse({ snapshots: (results || []).map(rowToSnapshot) });
}

export async function handleGetSnapshot(env, id, jsonResponse) {
  const row = await env.DB.prepare('SELECT * FROM extension_snapshots WHERE id = ?').bind(id).first();
  if (!row) return jsonResponse({ _error: 'Snapshot not found' }, 404);
  return jsonResponse(rowToSnapshot(row));
}

export async function handleGenerateSnapshot(env, extensionRef, body, user, jsonResponse) {
  // Resolve extension
  const ext = await env.DB.prepare(
    'SELECT * FROM extensions WHERE id = ? OR slug = ? LIMIT 1'
  ).bind(extensionRef, extensionRef).first();
  if (!ext) return jsonResponse({ _error: 'Extension not found' }, 404);
  if ((ext.type || 'mcp_generated') !== 'mcp_generated') {
    return jsonResponse({ _error: `Extension type '${ext.type}' does not support snapshot generation. Snapshots are for mcp_generated extensions.` }, 400);
  }

  const slug = body.slug ? slugify(body.slug) : '';
  if (!slug) return jsonResponse({ _error: 'slug required (e.g. "q2-handoff")' }, 400);

  const data = body.data || {};
  // Validate DATA against the extension's data_schema (if provided)
  const schema = safeParseJSON(ext.data_schema) || {};
  if (schema && Object.keys(schema).length > 0) {
    const result = validateData(data, schema);
    if (!result.ok) {
      return jsonResponse({ _error: 'DATA failed schema validation', validation_errors: result.errors }, 422);
    }
  }

  // Unique constraint per extension
  const existing = await env.DB.prepare(
    'SELECT id FROM extension_snapshots WHERE extension_id = ? AND slug = ?'
  ).bind(ext.id, slug).first();
  if (existing) return jsonResponse({ _error: `Snapshot slug '${slug}' already exists for this extension` }, 409);

  // Render HTML by substituting {{DATA}} in the template
  const dataJson = JSON.stringify(data);
  const html = String(ext.html || '').replace(/\{\{DATA\}\}/g, dataJson);

  // Write rendered HTML to R2
  const htmlKey = `extensions/${ext.slug}/${slug}.html`;
  try {
    await env.DOCS.put(htmlKey, html, {
      httpMetadata: { contentType: 'text/html; charset=utf-8' },
    });
  } catch (err) {
    return jsonResponse({ _error: `R2 write failed: ${err.message}` }, 500);
  }

  // Title: from body, or derive from ext name + slug
  const title = body.title || `${ext.name} — ${slug}`;
  const snapshotId = body.id || crypto.randomUUID();

  // Insert snapshot row (status defaults to 'draft', visibility to 'workspace')
  await env.DB.prepare(
    `INSERT INTO extension_snapshots
       (id, extension_id, slug, title, data, html_key, template_version, source_snapshot_id, status, visibility, reports_row_id, generated_at, generated_by)
     VALUES (?, ?, ?, ?, ?, ?, ?, ?, 'draft', ?, NULL, datetime('now'), ?)`
  ).bind(
    snapshotId,
    ext.id,
    slug,
    title,
    dataJson,
    htmlKey,
    ext.version,
    body.source_snapshot_id || null,
    body.visibility || 'workspace',
    user?.sub || ''
  ).run();

  // Also create a Draft row in the Reports DB so the user sees it pending publish
  try {
    const reportsRowId = crypto.randomUUID();
    const cells = {
      title,
      extension: ext.name,
      snapshot_slug: slug,
      status: 'Draft',
      visibility: (body.visibility || 'workspace') === 'public' ? 'Public' : 'Workspace',
      generated_at: new Date().toISOString().split('T')[0],
      generated_by: user?.name || user?.display_name || 'MCP',
      summary: body.summary || '',
      snapshot_id: snapshotId,
    };
    await env.DB.prepare(
      `INSERT INTO table_rows (id, table_id, cells, sort_order, archived, owner_user_id, created_at, updated_at)
       VALUES (?, ?, ?, 0, 0, 'default', datetime('now'), datetime('now'))`
    ).bind(reportsRowId, REPORTS_PAGE_ID, JSON.stringify(cells)).run();
    await env.DB.prepare(
      'UPDATE extension_snapshots SET reports_row_id = ? WHERE id = ?'
    ).bind(reportsRowId, snapshotId).run();
  } catch (err) {
    console.error('[extensions] failed to create Reports row:', err.message || err);
    // Non-fatal — snapshot exists, Reports row can be re-created later via publish
  }

  return jsonResponse({ ok: true, id: snapshotId, slug, html_key: htmlKey, status: 'draft' }, 201);
}

export async function handleUpdateSnapshot(env, id, body, jsonResponse) {
  const row = await env.DB.prepare('SELECT * FROM extension_snapshots WHERE id = ?').bind(id).first();
  if (!row) return jsonResponse({ _error: 'Snapshot not found' }, 404);

  const sets = [];
  const vals = [];
  const allowedScalar = ['title', 'visibility', 'status'];
  for (const key of allowedScalar) {
    if (key in body) { sets.push(`${key} = ?`); vals.push(body[key]); }
  }
  if ('data' in body) {
    // Re-validate + re-render HTML
    const ext = await env.DB.prepare('SELECT * FROM extensions WHERE id = ?').bind(row.extension_id).first();
    if (!ext) return jsonResponse({ _error: 'Parent extension missing' }, 500);
    const schema = safeParseJSON(ext.data_schema) || {};
    if (schema && Object.keys(schema).length > 0) {
      const result = validateData(body.data, schema);
      if (!result.ok) {
        return jsonResponse({ _error: 'DATA failed schema validation', validation_errors: result.errors }, 422);
      }
    }
    const dataJson = JSON.stringify(body.data);
    const html = String(ext.html || '').replace(/\{\{DATA\}\}/g, dataJson);
    try {
      await env.DOCS.put(row.html_key, html, { httpMetadata: { contentType: 'text/html; charset=utf-8' } });
    } catch (err) {
      return jsonResponse({ _error: `R2 write failed: ${err.message}` }, 500);
    }
    sets.push('data = ?'); vals.push(dataJson);
  }

  if (sets.length === 0) return jsonResponse({ _error: 'No valid fields to update' }, 400);
  vals.push(id);

  await env.DB.prepare(`UPDATE extension_snapshots SET ${sets.join(', ')} WHERE id = ?`).bind(...vals).run();

  // Mirror status/visibility changes into the linked Reports DB row if present
  if (row.reports_row_id && ('status' in body || 'visibility' in body || 'title' in body)) {
    try {
      const rowsBefore = await env.DB.prepare('SELECT cells FROM table_rows WHERE id = ?').bind(row.reports_row_id).first();
      if (rowsBefore) {
        const cells = safeParseJSON(rowsBefore.cells) || {};
        if ('status' in body) cells.status = body.status === 'published' ? 'Published' : 'Draft';
        if ('visibility' in body) cells.visibility = body.visibility === 'public' ? 'Public' : 'Workspace';
        if ('title' in body) cells.title = body.title;
        await env.DB.prepare(
          "UPDATE table_rows SET cells = ?, updated_at = datetime('now') WHERE id = ?"
        ).bind(JSON.stringify(cells), row.reports_row_id).run();
      }
    } catch (err) {
      console.error('[extensions] failed to mirror to Reports row:', err.message || err);
    }
  }

  return jsonResponse({ ok: true, id });
}

export async function handleDeleteSnapshot(env, id, jsonResponse) {
  const row = await env.DB.prepare('SELECT * FROM extension_snapshots WHERE id = ?').bind(id).first();
  if (!row) return jsonResponse({ _error: 'Snapshot not found' }, 404);
  // Delete R2 object first
  try { await env.DOCS.delete(row.html_key); } catch { /* ignore */ }
  // Delete linked Reports DB row
  if (row.reports_row_id) {
    try { await env.DB.prepare('DELETE FROM table_rows WHERE id = ?').bind(row.reports_row_id).run(); } catch { /* ignore */ }
  }
  await env.DB.prepare('DELETE FROM extension_snapshots WHERE id = ?').bind(id).run();
  return jsonResponse({ ok: true, id });
}

export async function handlePublishSnapshot(env, id, user, jsonResponse) {
  const row = await env.DB.prepare('SELECT * FROM extension_snapshots WHERE id = ?').bind(id).first();
  if (!row) return jsonResponse({ _error: 'Snapshot not found' }, 404);
  if (row.status === 'published') return jsonResponse({ ok: true, id, status: 'published', already: true });

  await env.DB.prepare(
    "UPDATE extension_snapshots SET status = 'published', published_at = datetime('now'), published_by = ? WHERE id = ?"
  ).bind(user?.sub || '', id).run();

  // Reflect into the Reports row
  if (row.reports_row_id) {
    try {
      const before = await env.DB.prepare('SELECT cells FROM table_rows WHERE id = ?').bind(row.reports_row_id).first();
      const cells = before ? (safeParseJSON(before.cells) || {}) : {};
      cells.status = 'Published';
      await env.DB.prepare(
        "UPDATE table_rows SET cells = ?, updated_at = datetime('now') WHERE id = ?"
      ).bind(JSON.stringify(cells), row.reports_row_id).run();
    } catch (err) {
      console.error('[extensions] failed to mark Reports row published:', err.message || err);
    }
  }

  return jsonResponse({ ok: true, id, status: 'published' });
}

export async function handleGetSnapshotData(env, id, jsonResponse) {
  const row = await env.DB.prepare(
    'SELECT id, extension_id, slug, title, data, template_version, status, visibility FROM extension_snapshots WHERE id = ?'
  ).bind(id).first();
  if (!row) return jsonResponse({ _error: 'Snapshot not found' }, 404);
  return jsonResponse({
    id: row.id,
    extension_id: row.extension_id,
    slug: row.slug,
    title: row.title,
    template_version: row.template_version,
    status: row.status,
    visibility: row.visibility,
    data: safeParseJSON(row.data) || {},
  });
}

// ─── Serve rendered HTML ───
// Public read endpoint — visibility check happens here.
// If snapshot.visibility === 'public': anyone can fetch.
// If snapshot.visibility === 'workspace': caller must be authenticated.
// `user` is null for unauthenticated callers; caller decides what to do
// with the result (the worker.js route wires this up).
export async function handleServeSnapshotHtml(env, extSlug, snapSlug, user, corsHeaders) {
  const row = await env.DB.prepare(
    `SELECT s.* FROM extension_snapshots s
     JOIN extensions e ON e.id = s.extension_id
     WHERE e.slug = ? AND s.slug = ? LIMIT 1`
  ).bind(extSlug, snapSlug).first();

  if (!row) {
    return new Response('Snapshot not found', { status: 404, headers: { ...corsHeaders, 'Content-Type': 'text/plain' } });
  }
  if (row.visibility !== 'public' && !user) {
    return new Response('Authentication required', { status: 401, headers: { ...corsHeaders, 'Content-Type': 'text/plain' } });
  }

  const obj = await env.DOCS.get(row.html_key);
  if (!obj) {
    return new Response('Snapshot HTML missing in storage', { status: 404, headers: { ...corsHeaders, 'Content-Type': 'text/plain' } });
  }
  return new Response(obj.body, {
    status: 200,
    headers: {
      ...corsHeaders,
      'Content-Type': 'text/html; charset=utf-8',
      'Cache-Control': 'no-store',
    },
  });
}

// ─── Link management (snapshot ↔ workspace records) ───
// Wraps existing tables: `neurons` / `neuron_nodes` for neuron links,
// `record_comments` for record-attached comments. Returned shape is
// uniform: { type, id, target_id, target_label, target_page_id, created_at }
//
// add_link body shape:
//   { kind: 'neuron', neuron_name?, neuron_id?, target_type, target_id, target_label?, page_config_id? }
//   { kind: 'record_comment', record_id, content }
//
export async function handleAddSnapshotLink(env, snapshotId, body, user, jsonResponse) {
  const snap = await env.DB.prepare(
    'SELECT id, slug, title, extension_id FROM extension_snapshots WHERE id = ?'
  ).bind(snapshotId).first();
  if (!snap) return jsonResponse({ _error: 'Snapshot not found' }, 404);

  const kind = body.kind;

  if (kind === 'neuron') {
    // Find or create the neuron, then add snapshot node + target node
    let neuronId = body.neuron_id;
    if (!neuronId) {
      const name = body.neuron_name || `${snap.title} connections`;
      neuronId = `neu_${crypto.randomUUID().replace(/-/g, '').slice(0, 12)}`;
      await env.DB.prepare(
        "INSERT INTO neurons (id, name, created_at, updated_at) VALUES (?, ?, datetime('now'), datetime('now'))"
      ).bind(neuronId, name).run();
    }
    // Add snapshot node (idempotent — check for existing first)
    const existingSnapNode = await env.DB.prepare(
      "SELECT id FROM neuron_nodes WHERE neuron_id = ? AND node_type = 'extension_snapshot' AND node_id = ?"
    ).bind(neuronId, snap.id).first();
    if (!existingSnapNode) {
      await env.DB.prepare(
        `INSERT INTO neuron_nodes (id, neuron_id, node_type, node_id, node_label, page_config_id, meta, created_at)
         VALUES (?, ?, 'extension_snapshot', ?, ?, '', '{}', datetime('now'))`
      ).bind(crypto.randomUUID(), neuronId, snap.id, snap.title).run();
    }
    // Add target node
    const targetNodeId = crypto.randomUUID();
    await env.DB.prepare(
      `INSERT INTO neuron_nodes (id, neuron_id, node_type, node_id, node_label, page_config_id, meta, created_at)
       VALUES (?, ?, ?, ?, ?, ?, '{}', datetime('now'))`
    ).bind(
      targetNodeId,
      neuronId,
      body.target_type || 'record',
      body.target_id,
      body.target_label || '',
      body.page_config_id || ''
    ).run();
    return jsonResponse({ ok: true, kind: 'neuron', neuron_id: neuronId, node_id: targetNodeId }, 201);
  }

  if (kind === 'record_comment') {
    if (!body.record_id || !body.content) return jsonResponse({ _error: 'record_id and content required' }, 400);
    const commentId = crypto.randomUUID();
    // page_config_id is needed by record_comments — look it up from the record
    let pageConfigId = body.page_config_id || '';
    if (!pageConfigId) {
      const rec = await env.DB.prepare('SELECT table_id FROM table_rows WHERE id = ?').bind(body.record_id).first();
      pageConfigId = rec?.table_id || '';
    }
    await env.DB.prepare(
      `INSERT INTO record_comments (id, record_id, page_config_id, user_id, user_name, content, created_at, updated_at)
       VALUES (?, ?, ?, ?, ?, ?, datetime('now'), datetime('now'))`
    ).bind(
      commentId,
      body.record_id,
      pageConfigId,
      user?.sub || 'mcp',
      user?.name || user?.display_name || 'MCP',
      body.content
    ).run();
    return jsonResponse({ ok: true, kind: 'record_comment', id: commentId }, 201);
  }

  return jsonResponse({ _error: `Unknown link kind: ${kind}` }, 400);
}

// List all links from a snapshot — aggregated from neurons + comments
export async function handleListSnapshotLinks(env, snapshotId, jsonResponse) {
  const snap = await env.DB.prepare('SELECT id, title FROM extension_snapshots WHERE id = ?').bind(snapshotId).first();
  if (!snap) return jsonResponse({ _error: 'Snapshot not found' }, 404);

  // Neurons containing this snapshot
  const neuronRows = await env.DB.prepare(
    `SELECT DISTINCT n.id as neuron_id, n.name as neuron_name
     FROM neurons n
     JOIN neuron_nodes nn ON nn.neuron_id = n.id
     WHERE nn.node_type = 'extension_snapshot' AND nn.node_id = ?`
  ).bind(snap.id).all();

  // For each neuron, get the other nodes (skipping the snapshot itself)
  const links = [];
  for (const n of (neuronRows.results || [])) {
    const others = await env.DB.prepare(
      `SELECT id, node_type, node_id, node_label, page_config_id, created_at
       FROM neuron_nodes
       WHERE neuron_id = ? AND NOT (node_type = 'extension_snapshot' AND node_id = ?)`
    ).bind(n.neuron_id, snap.id).all();
    for (const o of (others.results || [])) {
      links.push({
        kind: 'neuron',
        neuron_id: n.neuron_id,
        neuron_name: n.neuron_name,
        node_id: o.id,
        target_type: o.node_type,
        target_id: o.node_id,
        target_label: o.node_label,
        target_page_id: o.page_config_id,
        created_at: o.created_at,
      });
    }
  }

  return jsonResponse({ links });
}
